# batch 所需的 ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sync-mongodb-secret-batch-user
  namespace: kirakira-rosales

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kirakira-mongodb
  name: kirakira-mongodb-secrets-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kirakira-rosales
  name: kirakira-rosales-secrets-operator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kirakira-rosales
  name: kirakira-rosales-deployments-patch
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-kirakira-mongodb-secrets
  namespace: kirakira-mongodb
subjects:
- kind: ServiceAccount
  name: sync-mongodb-secret-batch-user
  namespace: kirakira-rosales
roleRef:
  kind: Role
  name: kirakira-mongodb-secrets-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operate-kirakira-rosales-secrets
  namespace: kirakira-rosales
subjects:
- kind: ServiceAccount
  name: sync-mongodb-secret-batch-user
  namespace: kirakira-rosales
roleRef:
  kind: Role
  name: kirakira-rosales-secrets-operator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-kirakira-rosales-deployments
  namespace: kirakira-rosales
subjects:
- kind: ServiceAccount
  name: sync-mongodb-secret-batch-user
  namespace: kirakira-rosales
roleRef:
  kind: Role
  name: kirakira-rosales-deployments-patch
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-mongodb-secret
  namespace: kirakira-rosales
spec:
  schedule: "0 6 * * 6"
  timeZone: "Asia/Shanghai"  # UTC+8
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sync-mongodb-secret-batch-user
          containers:
          - name: secret-copy
            image: cfdxkk01/kirakira-batch:0.0.13 # 请指定正确版本
            command: ["node", "./kirakira-batch/sync-mongodb-secret.js"]
            envFrom:
            - secretRef:
                name: kirakira-rosales-aws-ses-smtp-secret
          restartPolicy: OnFailure
