apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-mongodb-secret
  namespace: kirakira-rosales
spec:
  schedule: "0 6 * * 6"
  timeZone: "Asia/Shanghai"  # UTC+8
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: secret-copy
            image: cfdxkk01/kirakira-batch:0.0.1
            # command: ["node", "kirakira-batch/sync-mongodb-secret.js"]
            command: ["ls", "kirakira-batch"]
            envFrom:
            - secretRef:
                name: kirakira-rosales-aws-ses-smtp-secret
          restartPolicy: OnFailure
